### ISSUE TITLE
Dates in post titles

### ISSUE THREAD

**Issue by achennings** [remrama/readordie#7]
Just a note, I think having the date we post them as the title for readordie posts is kinda silly. they are cumbersome to type and they distract from the real information at the end. I would think that the date is something that should be implemented on the back-end so that the user does not have to deal with it.

**Comment by remrama** [comment]
ya u right.

I thought that was a requirement for jekyll to order the posts chronologically, but looked into it and I think the date in the header (officially "front matter") will only override the one from the filename, which should be enough for ordering. And also agree it should be removed from the blog titles.

>they are cumbersome to type

On that note -- I should say that _everything_ except for `layout` is technically optional. I'd like to *strongly suggest* adding the `author` too, so we know whose post is whose. But now I realize also that the `title` only overrides the inherent "title" in your filename.

**In general I think you're right to minimize the header requirements. Hold on resolution coming...**

**Comment by remrama** [comment]
Ok the blogpost header expectations have been largely reduced.

- **only _required_ variable is `layout`, which must always be `post`**
- the `date` and `title` of your post are just taken from the post filename (putting them in the header still works, it just overwrites the ones from filename so not really necessary)
- still *strong suggestion* for still including `author` in your post, only to know whose post is whose
- still option to include `article_doi`, which _if present_ will turn your blogpost title to a link to that address
- `tags` still optional

Also should note that if you aren't including something (eg `tags`), you do _not_ need to have a blank variable there, just leave it off the header completely.

All these ideas are updated in the [template file](https://github.com/remrama/readordie/master/_posts/2019-01-01-title-of-your-post.md).

Also the date is removed from the display of the post title (ie, when published online).
